/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSportsStreamRouteImport } from './routes/api.sports-stream'
import { Route as WatchTypeIdRouteImport } from './routes/watch.$type.$id'
import { Route as TmdbImgSizeFileRouteImport } from './routes/tmdb-img.$size.$file'
import { Route as TitleTypeIdRouteImport } from './routes/title.$type.$id'
import { Route as DownloadTvIdRouteImport } from './routes/download.tv.$id'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsStreamRoute = ApiSportsStreamRouteImport.update({
  id: '/api/sports-stream',
  path: '/api/sports-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchTypeIdRoute = WatchTypeIdRouteImport.update({
  id: '/watch/$type/$id',
  path: '/watch/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TmdbImgSizeFileRoute = TmdbImgSizeFileRouteImport.update({
  id: '/tmdb-img/$size/$file',
  path: '/tmdb-img/$size/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleTypeIdRoute = TitleTypeIdRouteImport.update({
  id: '/title/$type/$id',
  path: '/title/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadTvIdRoute = DownloadTvIdRouteImport.update({
  id: '/download/tv/$id',
  path: '/download/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/legal': typeof LegalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/support': typeof SupportRoute
  '/api/sports-stream': typeof ApiSportsStreamRoute
  '/download/tv/$id': typeof DownloadTvIdRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/tmdb-img/$size/$file': typeof TmdbImgSizeFileRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/legal': typeof LegalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/support': typeof SupportRoute
  '/api/sports-stream': typeof ApiSportsStreamRoute
  '/download/tv/$id': typeof DownloadTvIdRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/tmdb-img/$size/$file': typeof TmdbImgSizeFileRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/legal': typeof LegalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/support': typeof SupportRoute
  '/api/sports-stream': typeof ApiSportsStreamRoute
  '/download/tv/$id': typeof DownloadTvIdRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/tmdb-img/$size/$file': typeof TmdbImgSizeFileRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/legal'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sports'
    | '/support'
    | '/api/sports-stream'
    | '/download/tv/$id'
    | '/title/$type/$id'
    | '/tmdb-img/$size/$file'
    | '/watch/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/legal'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sports'
    | '/support'
    | '/api/sports-stream'
    | '/download/tv/$id'
    | '/title/$type/$id'
    | '/tmdb-img/$size/$file'
    | '/watch/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/legal'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sports'
    | '/support'
    | '/api/sports-stream'
    | '/download/tv/$id'
    | '/title/$type/$id'
    | '/tmdb-img/$size/$file'
    | '/watch/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LegalRoute: typeof LegalRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsRoute: typeof SportsRoute
  SupportRoute: typeof SupportRoute
  ApiSportsStreamRoute: typeof ApiSportsStreamRoute
  DownloadTvIdRoute: typeof DownloadTvIdRoute
  TitleTypeIdRoute: typeof TitleTypeIdRoute
  TmdbImgSizeFileRoute: typeof TmdbImgSizeFileRoute
  WatchTypeIdRoute: typeof WatchTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sports-stream': {
      id: '/api/sports-stream'
      path: '/api/sports-stream'
      fullPath: '/api/sports-stream'
      preLoaderRoute: typeof ApiSportsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$type/$id': {
      id: '/watch/$type/$id'
      path: '/watch/$type/$id'
      fullPath: '/watch/$type/$id'
      preLoaderRoute: typeof WatchTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tmdb-img/$size/$file': {
      id: '/tmdb-img/$size/$file'
      path: '/tmdb-img/$size/$file'
      fullPath: '/tmdb-img/$size/$file'
      preLoaderRoute: typeof TmdbImgSizeFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$type/$id': {
      id: '/title/$type/$id'
      path: '/title/$type/$id'
      fullPath: '/title/$type/$id'
      preLoaderRoute: typeof TitleTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/tv/$id': {
      id: '/download/tv/$id'
      path: '/download/tv/$id'
      fullPath: '/download/tv/$id'
      preLoaderRoute: typeof DownloadTvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LegalRoute: LegalRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsRoute: SportsRoute,
  SupportRoute: SupportRoute,
  ApiSportsStreamRoute: ApiSportsStreamRoute,
  DownloadTvIdRoute: DownloadTvIdRoute,
  TitleTypeIdRoute: TitleTypeIdRoute,
  TmdbImgSizeFileRoute: TmdbImgSizeFileRoute,
  WatchTypeIdRoute: WatchTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
